### ISSUE TITLE
error launching

### ISSUE THREAD

**Issue by pokkie123** [YuukiPS/Launcher-PC#10]
every time i click launch this error message comes up:

An error occurred trying to start the process
'C:Users\[user]\downloads\YuukiPS\mod\Cheat\GenshinImpact\Korepi\4.0.1\colorpicker.exe' with working directory
'C:\Users\[user]\downloadsYuukiPS'. The system cannot find the file specified.

what do i do?

**Comment by root-mega** [comment]
... it's literally there

**Comment by akbaryahya** [comment]
There are some cheats missing from `file.yuuki.me` so they cannot be downloaded, for the time being please turn off the cheat feature. In the future, you can customize the cheat folder without `file.yuuki.me` so you can choose which cheat you use or want to use
