### ISSUE TITLE
where

### ISSUE THREAD

**Issue by DarkVava** [YuukiPS/Launcher-PC#7]
![image](https://user-images.githubusercontent.com/123283351/213899419-a844c3d3-ed73-42ca-82c3-fde96417f533.png)

**Comment by mailpakokok** [comment]
What game version are you on ?

**Comment by Turkur** [comment]
Hey! i have the same problem game version 3.4
![Снимок экрана 2023-01-22 115645](https://user-images.githubusercontent.com/123287819/213902761-97122ead-93cc-43e8-93a6-294b9bc8584f.png)

**Comment by mailpakokok** [comment]
> Hey! i have the same problem game version 3.4 ![Снимок экрана 2023-01-22 115645](https://user-images.githubusercontent.com/123287819/213902761-97122ead-93cc-43e8-93a6-294b9bc8584f.png)

The launcher does not support version 3.4 yet same does the server. Please wait for it to be updated.

**Comment by DarkVava** [comment]
And how long is the wait approximately?

**Comment by mailpakokok** [comment]
Supports 3.4 on [2023.2.1.0446](https://github.com/YuukiPS/Launcher-PC/releases/tag/2023.2.1.0446)
